import { memo } from 'react';
import {
  Accessibility,
  Activity,
  AlignLeft,
  Anchor,
  ArrowDownRight,
  ArrowRight,
  ArrowUp,
  Atom,
  Bot,
  Braces,
  ChartLine,
  Check,
  CheckCheck,
  Cloud,
  Code,
  CodeXml,
  Container,
  Contrast,
  Cpu,
  Database,
  Download,
  Ear,
  FileCode,
  Frame,
  FlaskConical,
  Focus,
  GitBranch,
  GitCommitHorizontal,
  GitPullRequest,
  Gauge,
  Heading1,
  Image,
  KeyRound,
  Keyboard,
  LayoutPanelLeft,
  LayoutTemplate,
  Lock,
  Mail,
  MapPin,
  Menu,
  Moon,
  MousePointerClick,
  MoveDiagonal,
  MoveVertical,
  Package,
  Palette,
  Pause,
  Phone,
  Play,
  Plug,
  Printer,
  Radio,
  RefreshCw,
  ScanSearch,
  SearchCheck,
  Settings2,
  Share2,
  ShieldAlert,
  ShieldCheck,
  Square,
  SquareCheck,
  Sun,
  TestTube,
  TextCursor,
  TrendingUp,
  Triangle,
  Users,
  Volume2,
  Wind,
  Wrench,
  X,
  Zap,
} from 'lucide-react';

/**
 * Static registry mapping the kebab-case icon names used throughout
 * src/data/*.json to their lucide-react components, imported by name so
 * Vite/Rollup can tree-shake the ~1500-icon library down to only the ~60
 * icons this site actually uses. Importing the whole library via
 * `import * as icons` (the earlier approach) shipped a 760KB chunk; this
 * registry keeps the icon chunk under 10KB.
 */
const REGISTRY = {
  accessibility: Accessibility,
  activity: Activity,
  'align-left': AlignLeft,
  anchor: Anchor,
  'arrow-down-right': ArrowDownRight,
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  atom: Atom,
  bot: Bot,
  braces: Braces,
  'chart-line': ChartLine,
  check: Check,
  'check-check': CheckCheck,
  cloud: Cloud,
  code: Code,
  'code-xml': CodeXml,
  container: Container,
  contrast: Contrast,
  cpu: Cpu,
  database: Database,
  download: Download,
  ear: Ear,
  'file-code': FileCode,
  figma: Frame,
  'flask-conical': FlaskConical,
  focus: Focus,
  gauge: Gauge,
  'git-branch': GitBranch,
  'git-commit-horizontal': GitCommitHorizontal,
  'git-pull-request': GitPullRequest,
  'heading-1': Heading1,
  image: Image,
  'key-round': KeyRound,
  keyboard: Keyboard,
  'layout-panel-left': LayoutPanelLeft,
  'layout-template': LayoutTemplate,
  lock: Lock,
  mail: Mail,
  'map-pin': MapPin,
  menu: Menu,
  moon: Moon,
  'mouse-pointer-click': MousePointerClick,
  'move-diagonal': MoveDiagonal,
  'move-vertical': MoveVertical,
  package: Package,
  palette: Palette,
  pause: Pause,
  phone: Phone,
  play: Play,
  plug: Plug,
  printer: Printer,
  radio: Radio,
  'refresh-cw': RefreshCw,
  'scan-search': ScanSearch,
  'search-check': SearchCheck,
  'settings-2': Settings2,
  'share-2': Share2,
  'shield-alert': ShieldAlert,
  'shield-check': ShieldCheck,
  square: Square,
  'square-check': SquareCheck,
  sun: Sun,
  'test-tube': TestTube,
  'text-cursor': TextCursor,
  'trending-up': TrendingUp,
  triangle: Triangle,
  users: Users,
  'volume-2': Volume2,
  wind: Wind,
  wrench: Wrench,
  x: X,
  zap: Zap,
};

/** Renders a lucide icon by its kebab-case name (matches the icon names used in src/data/*.json). */
function IconBase({ name, size = 18, className, ...rest }) {
  const Cmp = REGISTRY[name];
  if (!Cmp) return null;
  return <Cmp size={size} aria-hidden="true" className={className} {...rest} />;
}

export const Icon = memo(IconBase);
